name: test_a

on:
  workflow_dispatch:  

#  push:
#    branches:
#      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake cmake-curses-gui build-essential
        g++ --version ## g++ (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
        cmake --version ##  3.31.3

    - run : |        
        sudo apt-get install -y libpcl-dev

    - run : |
        cd pcl 
        ls -la 
        cmake . 
        make -B 
        ./interactive_icp untitled.ply 100
        ls -la 
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests
      run: |
        python --version 

